### ISSUE TITLE
Queries with null do not work #cosmosEmulatorVnextPreview

### ISSUE THREAD

**Issue by jvalkeejarvi** [Azure/azure-cosmos-db-emulator-docker#122]
Following queries do not work:

```sql
SELECT * FROM c WHERE c.id = null
```

```sql
SELECT * FROM c WHERE c.id != null
```

**Comment by DmitriMelnikov** [comment]
Fix is checked in and will be available on the next release

**Comment by DmitriMelnikov** [comment]
The fix will be shipped in the post Nov27 release.

**Comment by xgerman** [comment]
@jvalkeejarvi can you please confirm that it's fixed in the latest version and close.

**Comment by jvalkeejarvi** [comment]
Seems to be working now. Thanks a lot!

**Comment by kmandalas** [comment]
@xgerman I don't know if related but Spring Data queries like this one:

` List<DemoAudit> findAllByPrincipalAndSubtypeIsNull(String principal);`

still fail, with error:

`System.NotSupportedException: Not supported function call IS_NULL with 1 arguments`

Integration test here: https://github.com/kmandalas/cosmosdb-vnext/blob/2791f59618583e719d2645064899b251ef738cc4/src/test/java/com/example/demo/audits/DemoAuditRepositoryIntegrationTest.java#L76

Is this related or should I open another issue?

**Comment by xgerman** [comment]
@kmandalas  Best to open a new issue so we can assign to our query team.
