### ISSUE TITLE
Not supported function call IS_NULL

### ISSUE THREAD

**Issue by kmandalas** [Azure/azure-cosmos-db-emulator-docker#143]
Spring Data queries like this one:

` List<DemoAudit> findAllByPrincipalAndSubtypeIsNull(String principal);`

fail, with error:

`System.NotSupportedException: Not supported function call IS_NULL with 1 arguments`

Integration test here: https://github.com/kmandalas/cosmosdb-vnext/blob/2791f59618583e719d2645064899b251ef738cc4/src/test/java/com/example/demo/audits/DemoAuditRepositoryIntegrationTest.java#L76

**Comment by DmitriMelnikov** [comment]
In progress

**Comment by DmitriMelnikov** [comment]
Our publish pipeline did not work until recently preventing the fixes from shipment. Pipeline is fixed now, and the fixes should be available. Please use ```docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview``` to download the latest image and ```docker inspect mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview``` to validate the latest build: Created field should be no less than 2024-12-16T20:25:13.18725592Z

**Comment by kmandalas** [comment]
@DmitriMelnikov pulled latest image ( "Created": "2024-12-16T20:23:52.276219413Z"). Error remains, full stacktrace below:

2024-12-18T12:09:00.441+02:00 DEBUG 87306 --- [           main] c.a.c.implementation.SqlQuerySpecLogger  : SELECT * FROM ROOT r WHERE (r.principal = @principal0 AND IS_NULL(r.subtype)) 
2024-12-18T12:09:00.566+02:00 ERROR 87306 --- [ctor-http-nio-1] c.a.c.i.query.DocumentProducer           : Unexpected failure, Context: n/a

```
com.azure.cosmos.CosmosException: {"innerErrorMessage":"System.NotSupportedException: Not supported function call IS_NULL with 1 arguments\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlFunctionCallScalarExpression sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 408\n   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression.Accept(SqlObjectVisitor visitor) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjects/SqlFunctionCallScalarExpression.cs:line 217\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.ProcessBinaryScalarExpression(SqlScalarExpression leftExpression, SqlScalarExpression rightExpression, SqlBinaryScalarOperatorKind operatorKind) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 208\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlBinaryScalarExpression sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 137\n   at Microsoft.Azure.Cosmos.SqlObjects.SqlBinaryScalarExpression.Accept(SqlObjectVisitor visitor) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjects/SqlBinaryScalarExpression.cs:line 39\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlWhereClause sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 1020\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlQuery sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 793\n   at Microsoft.Azure.Cosmos.SqlObjects.SqlQuery.Accept(SqlObjectVisitor visitor) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjects/SqlQuery.cs:line 48\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.HandleQueryRequestAsync(SqlRequest request, PostgresClient client, SqlQuerySpec querySpec, CancellationToken cancellation) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 462\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.ProcessRequestAsync(SqlRequest request, PostgresClient client) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 61\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlRequestPipeline.ProcessRequestAsync(KestrelHttpRequestContext transportRequest) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlRequestPipeline.cs:line 56, StatusCode: InternalServerError","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.54.0 MacOSX/14.6.1 JRE/21.0.2 az-sd-cos/5.9.1az-sp-cos/5.9.1","activityId":"50e76451-e709-449a-81d6-b42f976c391f","requestLatencyInMs":79,"requestStartTimeUTC":"2024-12-18T10:09:00.485935Z","requestEndTimeUTC":"2024-12-18T10:09:00.565893Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["primary"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatisticsList":[{"sessionToken":"0:-1#1","operationType":"Query","resourceType":"Document","statusCode":500,"subStatusCode":0,"requestCharge":0.0,"requestTimeline":[{"eventName":"connectionAcquired","startTimeUTC":"2024-12-18T10:09:00.486745Z","durationInMilliSecs":0.191},{"eventName":"connectionConfigured","startTimeUTC":"2024-12-18T10:09:00.486936Z","durationInMilliSecs":0.028},{"eventName":"requestSent","startTimeUTC":"2024-12-18T10:09:00.486964Z","durationInMilliSecs":0.336},{"eventName":"transitTime","startTimeUTC":"2024-12-18T10:09:00.487300Z","durationInMilliSecs":77.58},{"eventName":"received","startTimeUTC":"2024-12-18T10:09:00.564880Z","durationInMilliSecs":0.461}],"partitionKeyRangeId":null,"responsePayloadSizeInBytes":0,"exceptionMessage":"System.NotSupportedException: Not supported function call IS_NULL with 1 arguments\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlFunctionCallScalarExpression sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 408\n   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression.Accept(SqlObjectVisitor visitor) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjects/SqlFunctionCallScalarExpression.cs:line 217\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.ProcessBinaryScalarExpression(SqlScalarExpression leftExpression, SqlScalarExpression rightExpression, SqlBinaryScalarOperatorKind operatorKind) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 208\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlBinaryScalarExpression sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 137\n   at Microsoft.Azure.Cosmos.SqlObjects.SqlBinaryScalarExpression.Accept(SqlObjectVisitor visitor) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjects/SqlBinaryScalarExpression.cs:line 39\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlWhereClause sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 1020\n   at Microsoft.Azure.Cosmos.Postgres.Core.Query.SqlObjectPGTextSerializer.Visit(SqlQuery sqlObject) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjectPGTextSerializer.cs:line 793\n   at Microsoft.Azure.Cosmos.SqlObjects.SqlQuery.Accept(SqlObjectVisitor visitor) in /tmp/gateway/Cosmos.Postgres.Core/Query/SqlObjects/SqlQuery.cs:line 48\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.HandleQueryRequestAsync(SqlRequest request, PostgresClient client, SqlQuerySpec querySpec, CancellationToken cancellation) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 462\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.ProcessRequestAsync(SqlRequest request, PostgresClient client) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 61\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlRequestPipeline.ProcessRequestAsync(KestrelHttpRequestContext transportRequest) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlRequestPipeline.cs:line 56, StatusCode: InternalServerError","exceptionResponseHeaders":"{Transfer-Encoding=chunked, Server=PGSQL, x-ms-session-token=0:-1#1, x-ms-documentdb-partitionkeyrangeid=0, x-ms-interopandsdk-time-ms=74, x-ms-gatewayversion=2.0.0, Date=Wed, 18 Dec 2024 10:09:00 GMT, x-ms-activity-id=50e76451-e709-449a-81d6-b42f976c391f, Content-Type=application/json}"}],"samplingRateSnapshot":1.0,"systemInformation":{"usedMemory":"118055 KB","availableMemory":"9319129 KB","systemCpuLoad":"empty","availableProcessors":11},"clientCfgs":{"id":1,"machineId":"uuid:9aee1574-5461-4700-bf9d-9c912a975e48","connectionMode":"GATEWAY","numberOfClients":3,"excrgns":"[]","clientEndpoints":{"https://localhost:51902":3},"connCfg":{"rntbd":null,"gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: false, cs: false, rv: true)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])","proactiveInitCfg":"","e2ePolicyCfg":"","sessionRetryCfg":""}}}
	at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:478) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at com.azure.cosmos.implementation.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:504) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$1(RxGatewayStoreModel.java:365) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:782) ~[reactor-netty-http-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1349) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1389) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

**Comment by lionelc** [comment]
@kmandalas I double checked our release versions and it looks like the 2024-12-16 release doesn't include the change, where the fix was a couple days after the cutoff. We apologize for the inconvenience. It will be fixed in the next release cc: @DmitriMelnikov .

**Comment by xgerman** [comment]
@kmandalas we pushed a new version this morning which should have the fix. Please confirm.

**Comment by kmandalas** [comment]
@xgerman I was able to test after pulling latest image again. The operation now works. I guess we may close the issue.
