### ISSUE TITLE
Cosmos DB vNext Emulator Does not Support Numerical Partition Keys

### ISSUE THREAD

**Issue by MapFilterMagic** [Azure/azure-cosmos-db-emulator-docker#188]
**Describe the bug**
If you use a numerical partition key, you will not be able to find the document on a read where you specify the partition key or do a partial document update, which includes the partition key.

Pointed my application at the emulator and started running into problems. It can do a normal save (upsert) just fine. But the find and patch won't work.

Narrowed it down to the fact that our model's partition key is a `BigInteger`. Tried `int` and `long`, but it was still failing to findById (point read) or patch anything, both of which require you to supply the partition key. Then I changed it to a `String`, and it had no issues. Otherwise, it cannot find the document you are looking for by that partition key.

Confirmed copying over this gentleman's test code into a Spring Boot project (assume it has nothing to do with Spring Boot): https://github.com/bitxon/java-cosmos-emulator-vnext-experiment

**To Reproduce**
1. I copied over the code from https://github.com/bitxon/java-cosmos-emulator-vnext-experiment/blob/cdc42ee8704b53252afbc6bd8e96d557dcbd1934/src/test/java/bitxon/experiment/CosmosEmulatorVNextHttpTest.java

If you change the partition key to `/age`
* https://github.com/bitxon/java-cosmos-emulator-vnext-experiment/blob/cdc42ee8704b53252afbc6bd8e96d557dcbd1934/src/test/java/bitxon/experiment/CosmosEmulatorVNextHttpTest.java#L51

![Image](https://github.com/user-attachments/assets/e6120447-3234-48b3-83c8-1ddc050e642e)

And then feed in the age value instead of the name when dumping in a `new PartitionKey()` in both cases, you run into it

![Image](https://github.com/user-attachments/assets/e076ee33-7444-40f8-b53c-4c040764a78c)

![Image](https://github.com/user-attachments/assets/ba4a340b-470c-4b55-9231-dc904f5b4eba)

**Expected behavior**
Might have missed this when looking the unsupported feature list, but it should be able to support numeric partition keys like it does in the cloud.

**Desktop:**
 - OS: m1 macOS 15.3.2
 - **Version:** vNext Emulator latest
 - **SDK version:**
   - Java (jdk21)
   - `com.azure.spring:spring-cloud-azure-dependencies:5.21.0`
   - `org.springframework.boot:spring-boot-starter-parent:3.4.2`
   - `org.springframework.cloud: spring-cloud-dependencies:2024.0.0`
   - `com.azure.spring spring-cloud-azure-starter-data-cosmos`

**Comment by Amaan-Haque** [comment]
This issue has been fixed in the latest release. Please try it out!

**Comment by tagreine** [comment]
Hi,

I am still experiencing this issue with the latest emulator image (mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview).

Upsert with a numeric string partition key (e.g. "1") works, but read/find/patch does not.
Using an alphanumeric string (e.g. "1a") works as expected.

------------------------------------------------------------------------------

Here are sample logs/output:

Initializing Cosmos DB...

Database 'SampleDatabase' created or retrieved successfully.
Container 'Items' created or retrieved successfully.

=== Single Item Upsert ===
Upserted item with ID: 6ca79cd4-3a83-4a0d-a0a0-82b58401d681
Request charge: 0 RUs
Status code: Created
Upserted item: (ID: 6ca79cd4-3a83-4a0d-a0a0-82b58401d681), (PartitionKey: 1a)

=== Getting Specific Item ===
Retrieved item with ID: 6ca79cd4-3a83-4a0d-a0a0-82b58401d681
Request charge: 0 RUs
Retrieved: (ID:6ca79cd4-3a83-4a0d-a0a0-82b58401d681), (PartitionKey:1a)

=== Single Item Upsert ===
Upserted item with ID: d70084bd-1186-40c1-b5bb-84123a988f40
Request charge: 0 RUs
Status code: Created
Upserted item: (ID: d70084bd-1186-40c1-b5bb-84123a988f40), (PartitionKey: 1)

=== Getting Specific Item ===
Item with ID d70084bd-1186-40c1-b5bb-84123a988f40 not found in partition 1

![Image](https://github.com/user-attachments/assets/aa9245aa-3b11-4f9d-864f-a3a788bc6ed2)
![Image](https://github.com/user-attachments/assets/d2ec7e5d-32d3-4fd7-bfaf-ae848c89bd79)

------------------------------------------------------------------------------

Please let me know if there’s a workaround or if I should provide more details.
Thank you!

**Comment by Amaan-Haque** [comment]
Will investigate.

**Comment by Amaan-Haque** [comment]
Have identified the issue. The fix should be out in the next week!

**Comment by lionelc** [comment]
> Hey [@Amaan-Haque](https://github.com/Amaan-Haque), thank you for looking into this so promptly!
> 
> I'm curious - is this likely to be a regression, or an issue that's always been in place? I'm just looking to see if I can fix to an older tag to work around this 👍🏻

@ingalless We pushed a release yesterday https://github.com/Azure/azure-cosmos-db-emulator-docker/releases/tag/EN20250731 which included a bug fix on numerical partition key after last release. Can you please try again? 

If there's further issue with it, we would see if we can make a patch release. Thank you for your feedback and patience at this preview stage.
