### ISSUE TITLE
Exception: unknown type of jsonb container

### ISSUE THREAD

**Issue by WojciechNagorski** [Azure/azure-cosmos-db-emulator-docker#189]
**Describe the bug**
When we use `vnext-preview` (`"Created": "2025-03-31T20:30:17.306490938Z"`) image, sometimes we get the exception `unknown type of jsonb container`. The error occurs in various situations, even on methods that work. I managed to prepare mini reproductions.

**To Reproduce**
Run CosmosDB using the following command:
```
docker run --detach --publish 8081:8081 -e ENABLE_EXPLORER=false mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https
```
Run the mini-reproduction using this code: [cosmos-vnext-error-3-4-2025.zip](https://github.com/user-attachments/files/19586036/cosmos-vnext-error-3-4-2025.zip)

**Expected behavior**
The database should work without any problem.

**Desktop (please complete the following information):**
 - Latest Docker desktop on Windows + WSL integration

**Comment by WojciechNagorski** [comment]
Here is a full source code that reproduce this problem:
```c#
// See https://aka.ms/new-console-template for more information
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Linq;
using Newtonsoft.Json;
using System.Text.Json.Serialization;

var containerName = nameof(Feed) + "s";

var connectionString = "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";

var cosmosClientOptions = new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Gateway,
    ServerCertificateCustomValidationCallback = (_, _, _) => true
};
using CosmosClient cosmos = new(connectionString, cosmosClientOptions);

var database = await cosmos.CreateDatabaseIfNotExistsAsync(id:"MyDatabase", throughput: 400);

var containerProperties = new ContainerProperties(containerName, "/PartitionKey");
await database.Database.CreateContainerIfNotExistsAsync(containerProperties);

var container = cosmos.GetContainer("MyDatabase", containerName);

var feed1 = new Feed("Feed 1", "Project1", true, null);
var feed2 = new Feed("Feed 2", "Project2", false, ValidationDisciplineType.CORE1);

var result1 = await container.CreateItemAsync(feed1, new PartitionKey(feed1.PartitionKey));
Console.WriteLine($"\"{result1.Resource.Name}\" has been created for PartitionKey: {result1.Resource.PartitionKey}");
var result2 = await container.CreateItemAsync(feed2, new PartitionKey(feed2.PartitionKey));
Console.WriteLine($"\"{result2.Resource.Name}\" has been created for PartitionKey: {result2.Resource.PartitionKey}");

Console.WriteLine($"Getting data from partition \"{Feed.GetPartitionKey("Project1")}\"");
var query = container.GetItemLinqQueryable<Feed>(requestOptions: new QueryRequestOptions()
    { PartitionKey = new PartitionKey(Feed.GetPartitionKey("Project1")) });
var iterator = query.ToFeedIterator();
var feeds = new List<Feed>();

while (iterator.HasMoreResults)
{
    var response = await iterator.ReadNextAsync();
    feeds.AddRange(response);
}

Console.WriteLine("It should only return \"Feed 1\"!");
foreach (var feed in feeds)
{
    Console.WriteLine("Id: " + feed.Id);
    Console.WriteLine(" Name: " + feed.Name);
    Console.WriteLine(" Project: " + feed.ProjectName);
    Console.WriteLine(" PartitionKey: " + feed.PartitionKey);
}

try
{
    await container.DeleteItemAsync<Feed>(feed1.Id, new PartitionKey(feed1.PartitionKey));
}
catch (Exception ex)
{
    // Here is the exception :)
    Console.WriteLine("Error deleting item:");
    Console.WriteLine(ex.ToString());
}

public class Feed
{
    [System.Text.Json.Serialization.JsonConstructor]
    [Newtonsoft.Json.JsonConstructor]
    public Feed()
    {
        
    }

    public Feed(string name, string projectName, bool isOfficial, ValidationDisciplineType? validationDiscipline)
    {
        Id = GetId(projectName);
        Name = name;
        ProjectName = projectName;
        // IsOfficial = isOfficial;
        // ValidationDiscipline = validationDiscipline;
    }

    [JsonProperty("id")]
    [JsonPropertyName("id")]
    public string Id { get; init; }
    public string Name { get; set; }
    public string ProjectName { get; set; }

    public bool IsOfficial { get; set; }

    public ValidationDisciplineType? ValidationDiscipline { get; set; }

    public string PartitionKey => GetPartitionKey(this.ProjectName);

    public static string GetPartitionKey(string projectName) 
        => projectName.ToLower();

    public static string GetId(string projectName)
        => projectName.ToLower();
}

public enum ValidationDisciplineType
{
    CORE1,
    CORE2
}
```

**Comment by WojciechNagorski** [comment]
The exception:
```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 1c90f92f-1e07-4907-873f-5974308e76be; Reason: ({"code":"InternalServerError","message":"unknown type of jsonb container"}
RequestUri: https://127.0.0.1:8081/dbs/MyDatabase/colls/Feeds/docs/project1;
RequestMethod: DELETE;
Header: Authorization Length: 80;
Header: x-ms-date Length: 29;
Header: x-ms-documentdb-partitionkey Length: 12;
Header: x-ms-cosmos-sdk-supportedcapabilities Length: 1;
Header: x-ms-activity-id Length: 36;
Header: Cache-Control Length: 8;
Header: User-Agent Length: 79;
Header: x-ms-version Length: 10;
Header: Accept Length: 16;

ActivityId: 1c90f92f-1e07-4907-873f-5974308e76be, Request URI: /dbs/MyDatabase/colls/Feeds/docs/project1, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22621 cosmos-netstandard-sdk/3.37.10);
   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
--- Cosmos Diagnostics ---{"Summary":{"GatewayCalls":{"(500, 0)":1}},"name":"DeleteItemAsync","start datetime":"2025-04-03T11:34:39.040Z","duration in milliseconds":488.8283,"data":{"Client Configuration":{"Client Created Time Utc":"2025-04-03T11:34:37.5883278Z","MachineId":"hashedMachineName:e0296d7f-183e-69c2-55be-312f078bd496","NumberOfClientsCreated":1,"NumberOfActiveClients":1,"ConnectionMode":"Gateway","User Agent":"cosmos-netstandard-sdk/3.47.2|1|X64|Microsoft Windows 10.0.22621|.NET 8.0.14|N|","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":32}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":318.7412,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":318.6501,"data":{"System Info":{"systemHistory":[{"dateUtc":"2025-04-03T11:34:38.0880452Z","cpu":4.986,"memory":28961332.000,"threadInfo":{"isThreadStarving":"no info","availableThreads":32765,"minThreads":32,"maxThreads":32767},"numberOfOpenTcpConnection":0}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":318.6313,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":318.6192,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":318.5808,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":318.5737,"children":[{"name":"Microsoft.Azure.Cosmos.GatewayStoreModel Transport Request","duration in milliseconds":253.5886,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2025-04-03T11:34:39.0427332Z","DurationInMs":89.4116,"RequestUri":"https://127.0.0.1:8081/dbs/MyDatabase/colls/Feeds/docs/project1","ResourceType":"Document","HttpMethod":"DELETE","ActivityId":"1c90f92f-1e07-4907-873f-5974308e76be","StatusCode":"InternalServerError","ReasonPhrase":"Internal Server Error"}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"1c90f92f-1e07-4907-873f-5974308e76be","ResponseTimeUtc":"2025-04-03T11:34:39.3590137Z","StatusCode":500,"SubStatusCode":0,"RequestCharge":0,"RequestUri":"dbs/MyDatabase/colls/Feeds/docs/project1","ErrorMessage":"Microsoft.Azure.Documents.DocumentClientException: {\"code\":\"InternalServerError\",\"message\":\"unknown type of jsonb container\"}\r\nRequestUri: https://127.0.0.1:8081/dbs/MyDatabase/colls/Feeds/docs/project1;\r\nRequestMethod: DELETE;\r\nHeader: Authorization Length: 80;\r\nHeader: x-ms-date Length: 29;\r\nHeader: x-ms-documentdb-partitionkey Length: 12;\r\nHeader: x-ms-cosmos-sdk-supportedcapabilities Length: 1;\r\nHeader: x-ms-activity-id Length: 36;\r\nHeader: Cache-Control Length: 8;\r\nHeader: User-Agent Length: 79;\r\nHeader: x-ms-version Length: 10;\r\nHeader: Accept Length: 16;\r\n\r\nActivityId: 1c90f92f-1e07-4907-873f-5974308e76be, Request URI: /dbs/MyDatabase/colls/Feeds/docs/project1, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22621 cosmos-netstandard-sdk/3.37.10\r\n   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)","RequestSessionToken":null,"ResponseSessionToken":"0:-1#1","BELatencyInMs":null}}}]}]}]}]}]}]}]}
```

**Comment by lionelc** [comment]
> The exception:
> 
> ```
> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 1c90f92f-1e07-4907-873f-5974308e76be; Reason: ({"code":"InternalServerError","message":"unknown type of jsonb container"}
> RequestUri: https://127.0.0.1:8081/dbs/MyDatabase/colls/Feeds/docs/project1;
> RequestMethod: DELETE;
> Header: Authorization Length: 80;
> Header: x-ms-date Length: 29;
> Header: x-ms-documentdb-partitionkey Length: 12;
> Header: x-ms-cosmos-sdk-supportedcapabilities Length: 1;
> Header: x-ms-activity-id Length: 36;
> Header: Cache-Control Length: 8;
> Header: User-Agent Length: 79;
> Header: x-ms-version Length: 10;
> Header: Accept Length: 16;
> 
> ActivityId: 1c90f92f-1e07-4907-873f-5974308e76be, Request URI: /dbs/MyDatabase/colls/Feeds/docs/project1, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22621 cosmos-netstandard-sdk/3.37.10);
>    at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
>    at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
> --- Cosmos Diagnostics ---{"Summary":{"GatewayCalls":{"(500, 0)":1}},"name":"DeleteItemAsync","start datetime":"2025-04-03T11:34:39.040Z","duration in milliseconds":488.8283,"data":{"Client Configuration":{"Client Created Time Utc":"2025-04-03T11:34:37.5883278Z","MachineId":"hashedMachineName:e0296d7f-183e-69c2-55be-312f078bd496","NumberOfClientsCreated":1,"NumberOfActiveClients":1,"ConnectionMode":"Gateway","User Agent":"cosmos-netstandard-sdk/3.47.2|1|X64|Microsoft Windows 10.0.22621|.NET 8.0.14|N|","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":32}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":318.7412,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":318.6501,"data":{"System Info":{"systemHistory":[{"dateUtc":"2025-04-03T11:34:38.0880452Z","cpu":4.986,"memory":28961332.000,"threadInfo":{"isThreadStarving":"no info","availableThreads":32765,"minThreads":32,"maxThreads":32767},"numberOfOpenTcpConnection":0}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":318.6313,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":318.6192,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":318.5808,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":318.5737,"children":[{"name":"Microsoft.Azure.Cosmos.GatewayStoreModel Transport Request","duration in milliseconds":253.5886,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2025-04-03T11:34:39.0427332Z","DurationInMs":89.4116,"RequestUri":"https://127.0.0.1:8081/dbs/MyDatabase/colls/Feeds/docs/project1","ResourceType":"Document","HttpMethod":"DELETE","ActivityId":"1c90f92f-1e07-4907-873f-5974308e76be","StatusCode":"InternalServerError","ReasonPhrase":"Internal Server Error"}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"1c90f92f-1e07-4907-873f-5974308e76be","ResponseTimeUtc":"2025-04-03T11:34:39.3590137Z","StatusCode":500,"SubStatusCode":0,"RequestCharge":0,"RequestUri":"dbs/MyDatabase/colls/Feeds/docs/project1","ErrorMessage":"Microsoft.Azure.Documents.DocumentClientException: {\"code\":\"InternalServerError\",\"message\":\"unknown type of jsonb container\"}\r\nRequestUri: https://127.0.0.1:8081/dbs/MyDatabase/colls/Feeds/docs/project1;\r\nRequestMethod: DELETE;\r\nHeader: Authorization Length: 80;\r\nHeader: x-ms-date Length: 29;\r\nHeader: x-ms-documentdb-partitionkey Length: 12;\r\nHeader: x-ms-cosmos-sdk-supportedcapabilities Length: 1;\r\nHeader: x-ms-activity-id Length: 36;\r\nHeader: Cache-Control Length: 8;\r\nHeader: User-Agent Length: 79;\r\nHeader: x-ms-version Length: 10;\r\nHeader: Accept Length: 16;\r\n\r\nActivityId: 1c90f92f-1e07-4907-873f-5974308e76be, Request URI: /dbs/MyDatabase/colls/Feeds/docs/project1, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22621 cosmos-netstandard-sdk/3.37.10\r\n   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)","RequestSessionToken":null,"ResponseSessionToken":"0:-1#1","BELatencyInMs":null}}}]}]}]}]}]}]}]}
> ```

We pushed a new version for vnext-preview. Can you try that version?

**Comment by WojciechNagorski** [comment]
@lionelc It works right now! Thanks

**Comment by C0lpy** [comment]
Hey, i stumbeled upon this closed ticket, but it seems like iam still getting these error while running multiple tests, when i run them single this error doesnt occur

```
Message: 
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 9fae3131-9c60-41fd-8d06-fb63151b3716; Reason: ({"code":"InternalServerError","message":"unknown type of jsonb container"}
RequestUri: https://127.0.0.1:8081/dbs/----/colls/CodeMap/docs/737;
RequestMethod: DELETE;
Header: Authorization Length: 86;
Header: x-ms-date Length: 29;
Header: x-ms-documentdb-partitionkey Length: 13;
Header: x-ms-cosmos-sdk-supportedcapabilities Length: 1;
Header: x-ms-activity-id Length: 36;
Header: Cache-Control Length: 8;
Header: User-Agent Length: 90;
Header: x-ms-version Length: 10;
Header: Accept Length: 16;
Header: Request-Context Length: 49;
Header: Request-Id Length: 51;
Header: traceparent Length: 55;

ActivityId: 9fae3131-9c60-41fd-8d06-fb63151b3716, Request URI: /dbs//----//colls/CodeMap/docs/737, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.26100 cosmos-netstandard-sdk/3.36.0);; Diagnostics:{"Summary":{"GatewayCalls":{"(500, 0)":1}},"name":"DeleteItemAsync","start datetime":"2025-04-14T08:53:12.097Z","duration in milliseconds":34.8757,"data":{"Client Configuration":{"Client Created Time Utc":"2025-04-14T08:52:40.7025626Z","MachineId":"hashedMachineName:44be10b2-3b1e-5da5-0d4d-103c25ec737d","NumberOfClientsCreated":1,"NumberOfActiveClients":1,"ConnectionMode":"Gateway","User Agent":"cosmos-netstandard-sdk/3.43.1|1|X64|Microsoft Windows 10.0.26100|.NET 8.0.14|N|F 00000010|","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: True)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":12}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":34.5802,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":34.569,"data":{"System Info":{"systemHistory":[{"dateUtc":"2025-04-14T08:52:40.7291417Z","cpu":18.096,"memory":12844412.000,"threadInfo":{"isThreadStarving":"no info","availableThreads":32763,"minThreads":12,"maxThreads":32767},"numberOfOpenTcpConnection":0},{"dateUtc":"2025-04-14T08:52:50.7346210Z","cpu":29.887,"memory":12909124.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.1241,"availableThreads":32765,"minThreads":12,"maxThreads":32767},"numberOfOpenTcpConnection":0},{"dateUtc":"2025-04-14T08:53:00.7459231Z","cpu":27.369,"memory":12845372.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0656,"availableThreads":32765,"minThreads":12,"maxThreads":32767},"numberOfOpenTcpConnection":0},{"dateUtc":"2025-04-14T08:53:10.7636390Z","cpu":20.630,"memory":12815572.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.1002,"availableThreads":32765,"minThreads":12,"maxThreads":32767},"numberOfOpenTcpConnection":0}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":34.5657,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":34.5639,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":34.5512,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":34.55,"children":[{"name":"Microsoft.Azure.Cosmos.GatewayStoreModel Transport Request","duration in milliseconds":31.9505,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2025-04-14T08:53:12.0973051Z","DurationInMs":26.394,"RequestUri":"https://127.0.0.1:8081/dbs/Condor/colls/CodeMap/docs/737","ResourceType":"Document","HttpMethod":"DELETE","ActivityId":"9fae3131-9c60-41fd-8d06-fb63151b3716","StatusCode":"InternalServerError","ReasonPhrase":"Internal Server Error"}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"9fae3131-9c60-41fd-8d06-fb63151b3716","ResponseTimeUtc":"2025-04-14T08:53:12.1311096Z","StatusCode":500,"SubStatusCode":0,"RequestCharge":0,"RequestUri":"dbs/Condor/colls/CodeMap/docs/737","ErrorMessage":"Microsoft.Azure.Documents.DocumentClientException: {\"code\":\"InternalServerError\",\"message\":\"unknown type of jsonb container\"}\r\nRequestUri: https://127.0.0.1:8081/dbs/Condor/colls/CodeMap/docs/737;\r\nRequestMethod: DELETE;\r\nHeader: Authorization Length: 86;\r\nHeader: x-ms-date Length: 29;\r\nHeader: x-ms-documentdb-partitionkey Length: 13;\r\nHeader: x-ms-cosmos-sdk-supportedcapabilities Length: 1;\r\nHeader: x-ms-activity-id Length: 36;\r\nHeader: Cache-Control Length: 8;\r\nHeader: User-Agent Length: 90;\r\nHeader: x-ms-version Length: 10;\r\nHeader: Accept Length: 16;\r\nHeader: Request-Context Length: 49;\r\nHeader: Request-Id Length: 51;\r\nHeader: traceparent Length: 55;\r\n\r\nActivityId: 9fae3131-9c60-41fd-8d06-fb63151b3716, Request URI: /dbs/Condor/colls/CodeMap/docs/737, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.26100 cosmos-netstandard-sdk/3.36.0\r\n   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)","RequestSessionToken":null,"ResponseSessionToken":"0:-1#1","BELatencyInMs":null}}}]}]}]}]}]}]}]}

  Stack Trace: 
GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)

```

**Comment by ingalless** [comment]
Hey! I've also seen the issue when running multiple tests. We've reproduced this across multiple of our projects, and I've created a [simplified reproduction repository](https://github.com/ingalless/azure-cosmos-db-emulator-docker-issue-189-repro).

This uses the image tagged `mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-EN20250731` which was the latest available at the time of testing.

**Comment by lionelc** [comment]
> Hey! I've also seen the issue when running multiple tests. We've reproduced this across multiple of our projects, and I've created a [simplified reproduction repository](https://github.com/ingalless/azure-cosmos-db-emulator-docker-issue-189-repro).
> 
> This uses the image tagged `mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-EN20250731` which was the latest available at the time of testing.

I can confirm this is a Javascript-specific bug because we couldn't reproduce this issue in other SDKs. Need to dig deeper and check with that team. I will follow up.

**Comment by kyurkchyan** [comment]
I am experiencing this issue as well. For some reason tests randomly fail with this exception
```

Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 3f651ac0-...

Microsoft.Azure.Cosmos.CosmosException
Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 3f651ac0-6627-4e89-9b1f-e412a4578acf; Reason: ({"code":"InternalServerError","message":"unknown type of jsonb container"}
RequestUri: https://127.0.0.1:62046/dbs/test-05585103-127e-4cfd-9fd9-2f7b95fafc32/colls/SalesAgents/docs/ed3f44b3-7bc7-4846-a46f-0d30ff29fa5e;
RequestMethod: GET;
Header: Authorization Length: 82;
Header: x-ms-date Length: 29;
Header: x-ms-documentdb-partitionkey Length: 40;
Header: x-ms-cosmos-sdk-supportedcapabilities Length: 1;
Header: x-ms-activity-id Length: 36;
Header: Cache-Control Length: 8;
Header: User-Agent Length: 91;
Header: x-ms-version Length: 10;
Header: Accept Length: 16;

ActivityId: 3f651ac0-6627-4e89-9b1f-e412a4578acf, Request URI: /dbs/test-05585103-127e-4cfd-9fd9-2f7b95fafc32/colls/SalesAgents/docs/ed3f44b3-7bc7-4846-a46f-0d30ff29fa5e, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.26100 cosmos-netstandard-sdk/3.39.1);; Diagnostics:{"Summary":{"GatewayCalls":{"(500, 0)":1}},"name":"ReadItemAsync","start datetime":"2025-08-24T12:40:37.518Z","duration in milliseconds":22.2117,"data":{"Client Configuration":{"Client Created Time Utc":"2025-08-24T12:40:37.4964947Z","MachineId":"hashedMachineName:d7aec96e-fa55-0cf2-0018-e20c19db1d0d","NumberOfClientsCreated":103,"NumberOfActiveClients":2,"ConnectionMode":"Gateway","User Agent":"cosmos-netstandard-sdk/3.53.0|10|X64|Microsoft Windows 10.0.26100|.NET 9.0.8|DN|F 00000010|","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: True)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:True, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":32}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":22.137,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":22.1045,"data":{"System Info":{"systemHistory":[{"dateUtc":"2025-08-24T12:40:34.2315390Z","cpu":9.969,"memory":130034724.000,"threadInfo":{"isThreadStarving":"no info","availableThreads":32763,"minThreads":32,"maxThreads":32767},"numberOfOpenTcpConnection":0}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":22.1013,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":22.0992,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":22.0037,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":22.0027,"children":[{"name":"Microsoft.Azure.Cosmos.GatewayStoreModel Transport Request","duration in milliseconds":19.0128,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2025-08-24T12:40:37.5189455Z","DurationInMs":13.1645,"RequestUri":"https://127.0.0.1:62046/dbs/test-05585103-127e-4cfd-9fd9-2f7b95fafc32/colls/SalesAgents/docs/ed3f44b3-7bc7-4846-a46f-0d30ff29fa5e","ResourceType":"Document","HttpMethod":"GET","ActivityId":"3f651ac0-6627-4e89-9b1f-e412a4578acf","StatusCode":"InternalServerError","ReasonPhrase":"Internal Server Error"}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"3f651ac0-6627-4e89-9b1f-e412a4578acf","ResponseTimeUtc":"2025-08-24T12:40:37.5402849Z","StatusCode":500,"SubStatusCode":0,"RequestCharge":0,"RequestUri":"dbs/test-05585103-127e-4cfd-9fd9-2f7b95fafc32/colls/SalesAgents/docs/ed3f44b3-7bc7-4846-a46f-0d30ff29fa5e","ErrorMessage":"{\"code\":\"InternalServerError\",\"message\":\"unknown type of jsonb container\"}\r\nRequestUri: https://127.0.0.1:62046/dbs/test-05585103-127e-4cfd-9fd9-2f7b95fafc32/colls/SalesAgents/docs/ed3f44b3-7bc7-4846-a46f-0d30ff29fa5e;\r\nRequestMethod: GET;\r\nHeader: Authorization Length: 82;\r\nHeader: x-ms-date Length: 29;\r\nHeader: x-ms-documentdb-partitionkey Length: 40;\r\nHeader: x-ms-cosmos-sdk-supportedcapabilities Length: 1;\r\nHeader: x-ms-activity-id Length: 36;\r\nHeader: Cache-Control Length: 8;\r\nHeader: User-Agent Length: 91;\r\nHeader: x-ms-version Length: 10;\r\nHeader: Accept Length: 16;\r\n\r\nActivityId: 3f651ac0-6627-4e89-9b1f-e412a4578acf, Request URI: /dbs/test-05585103-127e-4cfd-9fd9-2f7b95fafc32/colls/SalesAgents/docs/ed3f44b3-7bc7-4846-a46f-0d30ff29fa5e, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.26100 cosmos-netstandard-sdk/3.39.1","RequestSessionToken":null,"ResponseSessionToken":"0:-1#1","BELatencyInMs":null}}}]}]}]}]}]}]}]}
   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
```

I am using `mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview` sha256:2179ac035a332e9fdd7f7deb6a025b20465572375250be6a7a4479c40b096aaf

**Comment by lionelc** [comment]
Just to let everyone know that we just made a new release with an upgraded query engine, which improved query a lot. Please try it out: https://github.com/Azure/azure-cosmos-db-emulator-docker/releases/tag/vnext-EN20251118 .

I am closing the issue now but feel free to reopen it if there's any further issue. Thank you for your feedback, your patience and your support to the community which makes the product better.
